# Generated by Django 3.0.4 on 2020-03-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
