# Generated by Django 3.0.4 on 2020-03-27 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogpost_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 13, 43, 52, 931696, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
