# Generated by Django 3.0.4 on 2020-03-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200327_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='last_modified',
            field=models.DateTimeField(editable=False),
        ),
    ]
