# Generated by Django 3.0.5 on 2020-04-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200401_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='html_content',
            field=models.TextField(default=''),
        ),
    ]
