# Generated by Django 3.0.5 on 2020-04-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_blogpost_html_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='header_image_url_wide',
            field=models.URLField(blank=True),
        ),
    ]
