# Generated by Django 3.0.7 on 2020-09-20 20:16

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True)),
                ('content', martor.models.MartorField(max_length=500)),
                ('html_content', models.TextField(default='')),
                ('created_at', models.DateTimeField(editable=False)),
                ('last_modified', models.DateTimeField(editable=False)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
